[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:tiup-visualizer]
command=/app/tiup-visualizer
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/tiup-visualizer-stdout.log
stderr_logfile=/var/log/tiup-visualizer-stderr.log
environment=LISTEN_ADDR=":8000"

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx-stdout.log
stderr_logfile=/var/log/nginx-stderr.log
